### ISSUE TITLE
Support properties with multiple types (nullables)

### ISSUE THREAD

**Issue by thinkberg** [moviepilot/blumquist#6]
```
# Notification
- total: (number, required)
- notifications: (array[string], required)
```
Fails with ```{"total":1, "notifications": ["a"]}``` apparently because the type_def now contains an array for the ```type_def[:type]``` (```["number"]```, instead of ```"number"```) at ```blumquist-0.3.2/lib/blumquist.rb:67```

**Comment by jayniz** [comment]
Can you provide code to reproduce?

**Comment by thinkberg** [comment]
It is bascially what I provides. In a schema, properties types are now an array and not a string even for primitive types:

```
"type": "object",
      "properties": {
        "total": {
          "type": [
            "number"
          ],
          "description": ""
        },
        "notifications": {
          "type": [
            "array"
          ],
          "description": "",
          "items": [
            {
              "type": "object",
              "oneOf": [
                {
                  "$ref": "#/definitions/project::notification"
                }
              ]
            }
          ]
        }
      }
```

**Comment by thinkberg** [comment]
Actually, it looks more like a bug in the schema. if the type is "object" it is a string, else an array.

**Comment by jayniz** [comment]
Do you also have data that should pass but doesn't?

**Comment by thinkberg** [comment]
it fails with ```{total: 1}``` if you remove notifications from the schema above

**Comment by jayniz** [comment]
So, the test case is this?

schema:
```json
{
  "type": "object",
  "properties": {
    "total": {
      "type": [
        "number"
      ]
    }
  }
}
```

data:
```json
{"total": 1}
```

**Comment by thinkberg** [comment]
Of course.
